[params.author]
name = "Nicholas Ho JX"
headline = "DevSecOps Engineer"
bio = "A software engineer with a focus on DevSecOps"
links = [
  { github = "https://github.com/Nicholas-Ho" }
  { linkedin = "https://www.linkedin.com/in/nicholas-ho-jx" }
]