[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 20

[[main]]
  pre = "github"
  name = "GitHub"
  url = "https://github.com/Nicholas-Ho"
  weight = 30

[[main]]
  pre = "linkedin"
  name = "LinkedIn"
  url = "https://linkedin.com/in/nicholas-ho-jx"
  weight = 30