colorScheme = "blowfish"
disableImageOptimization = false
defaultBackgroundImage = "img/singapore-skyline.jpg"

[homepage]
  layout = "background"
  homepageImage = "img/singapore-skyline.jpg"
  layoutBackgroundBlur = true
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "posts"
  cardView = true
  cardViewScreenWidth = false

[header]
  layout = "fixed"

[article]
  showHero = true
  heroStyle = "background" 
  showSummary = true
  showTableOfContents = true
  showRelatedContent = false

[list]
  showCards = true
  groupByYear = false
  cardView = true